## Lesson 5

In [1]:
import numpy as np

1.a

In [2]:
my_info = np.array(["Jenna", "Maratea", "Pennsylvania", "Purple"])
my_info_new = np.char.upper(my_info)
my_info_new

array(['JENNA', 'MARATEA', 'PENNSYLVANIA', 'PURPLE'], dtype='<U12')

1.b

In [7]:
count_a = np.char.count(my_info ,  'a')
count_a

array([1, 3, 2, 0])

2.a

In [17]:
odd_nums = np.arange(1, 43, 2)
odd_nums

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41])

1.a

In [13]:
sum_odd = np.sum(odd_nums)
sum_odd

441

In [22]:
odd_floats = odd_nums.astype(float)
product_odd = np.prod(odd_floats)
product_odd

1.3113070457687988e+25

2.b

In [23]:
odd_log = np.log(odd_nums)
odd_log

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898,
       3.04452244, 3.13549422, 3.21887582, 3.29583687, 3.36729583,
       3.4339872 , 3.49650756, 3.55534806, 3.61091791, 3.66356165,
       3.71357207])